### PR TITLE
Linux build for m71

### PR DESCRIPTION
**Pull request by OlegKrymskyi**

### CODE REVIEW

**Comment by djee-ms** [comment]
Hi @OlegKrymskyi, many thanks for opening this PR. I'll try to get some time to review it, but already I can tell by policy we're unlikely to be able to commit a prebuilt binary file (`.so`) into this repository, for security reasons. Can you please try to avoid it? Thanks!

**Review by jehumb-havok — CHANGES_REQUESTED** [review]
-

**Comment by OlegKrymskyi** [comment]
> Hi @OlegKrymskyi, many thanks for opening this PR. I'll try to get some time to review it, but already I can tell by policy we're unlikely to be able to commit a prebuilt binary file (`.so`) into this repository, for security reasons. Can you please try to avoid it? Thanks!

Yes, sure, I will remove this file. I hope in the next release version it will be a part of the nuget :)

**Comment by joshdixon** [comment]
Hey @OlegKrymskyi, I've been trying out your linux example and it seems to work until I try to use a TURN server. I get the following:
image

Any ideas?

**Comment by OlegKrymskyi** [comment]
@joshdixon Try to run it with the same setting on windows. Do you have the same error?

**Comment by OlegKrymskyi** [comment]
@joshdixon Besides, you can try to check your TURN server first: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

**Comment by joshdixon** [comment]
> @joshdixon Besides, you can try to check your TURN server first: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

Yep you're right, was an issue with the TURN server. Cheers for the swift reply!

**Comment by jehumb-havok** [comment]
Closing PR ahead of disabling, as per Microsoft Mixed Reality organization decision.

**Pull request closed without merging**
